### ISSUE TITLE
Support for private organizations

### ISSUE THREAD

**Issue by juliocamarero** [Bitergia/cauldron.io#1]
Hi there, 

I was trying to use cauldron for a private organization in github and it seems the information is not loaded. Other apps that follow a similar approach would ask me to authorize the app to read my private repos and organizations and this one didn't ask for it. I think it should be easy to solve just adding that to the oauth part.

**Comment by jgbarah** [comment]
Thanks a lot,, @juliocamarero for your feedback. In this case, not analyzing private repos is intentional. Since dashboards are public, some people may not realize that they could be leaking private information to the public dashboard, including for example the headers of issues and pull requests (or commits, for that matter), and not only the overall activity. To avoid potential problems with people not realizing the implications of analyzing private repositories, being the result public, we're using oauth tokens that need permissions only for public repos.

Of course, that service is provided by Bitergia, but not under the public Cauldron.

Sorry for the inconvenience.

**Comment by juliocamarero** [comment]
Thanks a lot for the explanation @jgbarah :)
That makes sense.

I am already trying to obtain access to the service provided by Bitergia 👍
