### ISSUE TITLE
Dashboard for the Odoo Community Association

### ISSUE THREAD

**Issue by dreispt** [Bitergia/cauldron.io#3]
Hello, we at the OCA are looking for tools to help us recognize contributions to the projects/repositories under the OCA umbrella.

The cauldron.io dashboards seem an excellent tool for that. Unfortunately it look like the data is not being updated.

Would it be appropriate for a non-profit organization like the OCA to use your dahboards?
What should we do to keep the data updated?

![image](https://user-images.githubusercontent.com/1246629/29289237-937ea848-8133-11e7-97e4-2c084d89c145.png)

Thanks is advance

**Comment by jsmanrique** [comment]
Hi,

Sorry for the long delay answering.

You have several options to keep your data updated:

1) You can use "Refresh" button to refresh the data for the current repositories

2) Since Cauldron only gets data for the latest 30 active repositories, from time to time, those repositories can change. After 30 days, the dashboards are removed if they are not refreshed. Once your dashboard is removed, you can ask for a new one, with the latest 30 active repositories on that moment.

3) You can build your own dashboard following [current documentation](https://www.gitbook.com/book/grimoirelab/grimoirelab-training/details)

4) You can hire [Bitergia](http://bitergia.com) to build, host and maintain a complete dashboard (covering all github repositories and other data sources supported by [GrimoireLab](http://grimoirelab.github.io/)).

Sadly, it seems Cauldron is not working today :-(. Issue opened #4

**Comment by jsmanrique** [comment]
It seems that Cauldron site is working now.
